version: '3.1'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: henange01750/brl_docker:brl_backend_v1
    container_name: myapp
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: spring_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  mysql-data:
