version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: brl-app
    build:
      context: .  # Assurez-vous que votre Dockerfile est au même niveau que ce docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapper le port de l'application
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/spring_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    container_name: brl-db
    ports:
      - "3307:3306"  # Gardez le port par défaut pour éviter toute confusion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
