version: '3.1'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: spring_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: henange01750/brl_docker:brl_backend_v1
    container_name: myapp
    depends_on:
      - mysql
    environment:
      
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/spring_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: MYSQL_PASSWORD:root
    ports:
      - "8080:8080"
    links:
      - mysql

volumes:
  mysql-data:
